### model
model_name_or_path: /home/inno/.cache/modelscope/hub/models/Qwen/Qwen3.5-4B/
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all

### dataset
dataset: colon_train
eval_dataset: colon_val
template: qwen3_5_nothink
# template: qwen3_5
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: /media/inno/work_dirs/LLM/LlamaFactory/colon/outputs-sft-qwen3.5-4b-v1
logging_steps: 10
save_strategy: epoch
eval_strategy: epoch
save_total_limit: 13
load_best_model_at_end: true
metric_for_best_model: eval_loss
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_steps: 5
weight_decay: 0.05
bf16: true
ddp_timeout: 30000
gradient_checkpointing: true
